apiVersion: v1
kind: Service
metadata:
    name: bryanvillalpandotrujillowebapinet
spec:
    type: LoadBalancer
    ports:
    - port: 8081/tcp 
    selector:
        app: bryanvillalpandotrujillowebapinet